# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push new build to the TestFlight"
  lane :beta do

  match(type: 'appstore', app_identifier: "abedalkareem.MyApp", readonly: true)

  build_number = increment_build_number
  version_number = increment_version_number(bump_type: "patch")

  add_badge(shield: "#{version_number}-#{build_number}-red")

  gym(scheme: "MyApp")

  pilot(username: "your_email@yahoo.com")

  slack(message: "App successfully released!", slack_url: "slack_url")

  end

end
